show_fullname_in_mentions:
  default: true
  description:
    en: "If enabled @mentions will show the @fullname instead of the @username"
    pt_BR: "Se ativado @mencoes exibirá @nomecompleto ao invés de @usuario"
show_fullname_for_groups:
  default: true
  description:
    en: "If enabled group @mentions will also show the @fullname instead of the @groupname"
    pt_BR: "Se ativado @mencoes de grupos também exibirão @nomecompleto ao invés de @grupo"
